version: '3.7'

services:
  mysql:
    container_name: catalogo_de_videos_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=catalogo_de_videos
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    networks:
      - default

networks:
  default:

volumes:
  db_data:
